### ISSUE TITLE
请帮我看看这是什么问题。。。。。。

### ISSUE THREAD

**Issue by lhackercoco** [Skymine/xiangrikui-exp#1]
Exception in thread Thread-548:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
Exception in thread Thread-867:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
Exception in thread Thread-619:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-719:
Exception in thread Thread-711:
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-883:
    raise Empty
_queue.Empty
Exception in thread Thread-288:
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Traceback (most recent call last):
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/queue.py", line 179, in get
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    raise Empty
_queue.Empty
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
Traceback (most recent call last):
    self.run()
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    self.run()
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    raise Empty
_queue.Empty
    raise Empty
_queue.Empty
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
Exception in thread Thread-1523:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-1520:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-1505:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-1597:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-1610:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-1501:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-1587:
Traceback (most recent call last):
Exception in thread Thread-1495:
Exception in thread Thread-1524:
Exception in thread Thread-1563:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-1545:
Traceback (most recent call last):
Exception in thread Thread-1586:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-1531:
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    port = port_queue.get(timeout=20)
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-1535:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/usr/lib/python3.9/queue.py", line 179, in get
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    raise Empty
_queue.Empty
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    raise Empty
_queue.Empty
    self.run()
    self._target(*self._args, **self._kwargs)
    port = port_queue.get(timeout=20)
    port = port_queue.get(timeout=20)
    raise Empty
_queue.Empty
    raise Empty
_queue.Empty
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
  File "/usr/lib/python3.9/threading.py", line 892, in run
    port = port_queue.get(timeout=20)
    port = port_queue.get(timeout=20)
_queue.Empty
    raise Empty
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
  File "/usr/lib/python3.9/queue.py", line 179, in get
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
  File "/usr/lib/python3.9/queue.py", line 179, in get
_queue.Empty
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
    raise Empty
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
    self._target(*self._args, **self._kwargs)
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
  File "/home/xiangrikui-exp/exp.py", line 46, in worker
_queue.Empty
    raise Empty
_queue.Empty
    port = port_queue.get(timeout=20)
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
_queue.Empty
    raise Empty
    raise Empty
_queue.Empty
_queue.Empty
Exception in thread Thread-2068:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
Exception in thread Thread-2106:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Thread-2920:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
Exception in thread Thread-2905:
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Exception in thread Thread-2255:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-2846:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
OSError: [Errno 24] Too many open files
Exception in thread Thread-2800:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
Exception in thread Thread-2412:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
Exception in thread Thread-2168:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-2406:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
    self._target(*self._args, **self._kwargs)
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
Exception in thread Thread-2313:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/home/xiangrikui-exp/exp.py", line 43, in worker
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files

**Comment by Skymine** [comment]
这是线程数大于队列中的任务数了，所以有些线程取不到任务，不影响执行，就是有点不好看，我更新个版本吧，把这个异常抛掉

**Comment by Skymine** [comment]
另外你执行脚本的环境对端口打开数量有限制，你可以把端口扫描线程数降低一点
